### PR TITLE
Multitple orders shows all orders with products list

### PR DESCRIPTION
**Pull request by prafullatass**
# Description
when the user clicks on multiple orders, the user sees a list of customer names that have incomplete orders more than one with a list of orders that includes the products on those orders

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Testing Instructions for Change Made
1. `git fetch --all`
1. `git checkout praful
1.open in VS and run
1. click on reports and then on multiple orders

# Checklist:
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [ X] My changes generate no new warnings

# Ticket:
https://github.com/nss-day-cohort-30/bangazon-site-billowy-beluga/issues/12

### CODE REVIEW

**Review by justinavickers — DISMISSED** [review]
👍

**Review by katfree — APPROVED** [review]
AWESOME

**Review by justinavickers — APPROVED** [review]
👍

**Review by warnercarpenter — APPROVED** [review]
GoOd JoB!

**Pull request merged**
